In [4]:
import torch
torch.__version__

'2.2.1+cpu'

In [5]:
x =torch.rand(5,3)
x

tensor([[0.9504, 0.5480, 0.5034],
        [0.7112, 0.2439, 0.7387],
        [0.1250, 0.0888, 0.5447],
        [0.7951, 0.4930, 0.1547],
        [0.2951, 0.0184, 0.3433]])

In [22]:
x = torch.rand(1)
b = torch.rand(1, requires_grad = True)
w = torch.rand(1, requires_grad = True)
y = w * x
z = y + b

In [23]:
x.requires_grad, b.requires_grad, w.requires_grad, y.requires_grad, z.requires_grad

(False, True, True, True, True)

In [24]:
x

tensor([0.7398])

backward

In [25]:
z.backward(retain_graph=True) # 如果不清空，会累加起来

In [26]:
w.grad

tensor([0.7398])

In [27]:
b.grad


tensor([1.])